let bool = true;
console.log(bool);
bool = false;
console.log(bool); 
bool = true && false;
bool = false && true;
bool = false && false;
bool = true && true;
console.log(bool);
bool = true || false;
bool = false || true;
bool = false || false;
bool = true || true;
console.log(bool);
bool = !true;
console.log(bool);
bool = !false;
console.log(bool);

bool = (true && false || true) && (!false || (false && true));
console.log(bool);

bool = 10 > 5;
bool = 10 < 5;
bool = 10 > 10;
bool = 10 < 10;
bool = 10 == 10;
bool = '10' == 10;
bool = '10' === 10;
bool = 10 >= 10;
bool = 10 <= 10;
bool = '10' != 10;
bool = '10' !== 10;
bool = [] == '';
console.log(bool);